routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Blog\LikeController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
//use App\Http\Controllers\Admin\OrderController;
use \App\Http\Controllers\Blog\CommentController;
use \App\Http\Controllers\Blog\PageController;

Route::get('/', [ContentController::class, 'index'])
    ->name('index');
Route::post('/order_from_client', [ContentController::class, 'orderFromClient'])
    ->name('index.order_from_client');
Route::get('/contacts', [ContentController::class, 'contacts'])
    ->name('index.contacts');

Route::get('/contact', function () {
    return view('contact');
});

//Auth::routes();

//Route::get('/test', [App\Http\Controllers\TestController::class, 'testFib'])->name('test');
//Route::get('/river', [App\Http\Controllers\TestController::class, 'river'])->name('river');

Route::group(['middleware' => 'role:admin'], function() {
    Route::get('/dashboard', function() {
        return 'Добро пожаловать, Веб-разработчик';
    });
});



//Админка
Route::middleware(['role:admin'])->prefix('admin')->group(function() {
    Route::get('/home', [AdminHomeController::class, 'home'])->name('admin.home');
});

Route::group(['middleware' => 'role:admin'], function() {
    Route::prefix('admin')->namespace('App\Http\Controllers\Admin')->group(function() {
        //Routes для поиска
        Route::get('/orders/search', 'OrderController@search')
            ->name('admin.orders.search');
        Route::resource('/orders', 'OrderController')
            ->names('admin.orders');
//        Route::get('/orders/search', [OrderController::class, 'search'])->name('admin.orders.search');
//        Route::resource('orders', OrderController::class)->names('admin.orders');

        Route::get('/posts/search', 'PostController@search')
            ->name('admin.posts.search');
        Route::post('/posts/upload-file', 'PostController@uploadImage')
            ->name('admin.posts.upload_file');
        Route::resource('/posts', 'PostController')
            ->names('admin.posts');

        Route::get('/post_categories/search', 'PostCategoryController@search')
            ->name('admin.post_categories.search');
        Route::resource('/post_categories', 'PostCategoryController')
            ->names('admin.post_categories');

        Route::get('/manufacturers/search', 'ManufacturerController@search')
            ->name('admin.manufacturers.search');
        Route::resource('/manufacturers', 'ManufacturerController')
            ->names('admin.manufacturers');

        Route::get('/type_of_technics/search', 'TypeOfTechnicController@search')
            ->name('admin.type_of_technics.search');
        Route::resource('/type_of_technics', 'TypeOfTechnicController')
            ->names('admin.type_of_technics');


        Route::get('/users/search', 'UserController@search')
            ->name('admin.users.search');
        Route::resource('/users', 'UserController')
            ->names('admin.users');
        Route::get('/users/staffs', 'StaffController@search')
            ->name('admin.staffs.search');
        Route::resource('/staffs', 'StaffController')
            ->names('admin.staffs');

        Route::get('/chats', 'ChatController@index')
            ->name('admin.chats.index');
        Route::get('/chats/{chat_id}', 'ChatController@show')
            ->name('admin.chats.show');
        Route::post('/chats/store', 'ChatController@store')
            ->name('admin.chats.store');
    });
});

Auth::routes();
Route::prefix('blog')->namespace('App\Http\Controllers\Blog')->group(function() {

    Route::get('/home', [HomeController::class, 'home'])->name('blog.home');

    Route::get('/posts', 'PostController@index')
        ->name('blog.posts.index');
    Route::get('/by-category/{category}', 'PostController@indexByCategory')
        ->name('blog.posts.by-category');
    Route::get('/posts/{slug}', 'PostController@show')
        ->name('blog.posts.show');

    Route::post('/posts/set-like', [LikeController::class, 'setLike'])
        ->name('blog.posts.set-like');

    Route::post('/posts/set-comment', [CommentController::class, 'setComment'])
        ->name('blog.posts.set-comment');

    //pages
    Route::get('/contacts', [PageController::class, 'contacts'])
        ->name('blog.contacts');

    Route::get('/gallery', [PageController::class, 'gallery'])
        ->name('blog.gallery');

    Route::get('/about-us', [PageController::class, 'aboutUs'])
        ->name('blog.about-us');


//    Route::get('/', 'PostController@show')
//        ->name('template_blog.index.category');

//    Route::get('/orders/search', 'OrderController@search')
//        ->name('admin.orders.search');
//    Route::resource('/orders', 'OrderController')
//        ->names('admin.orders');

});


Route::get('/dryer', ['as' => 'index.dryer', 'uses' => 'App\Http\Controllers\ContentController@dryer']);
Route::get('/sd', ['as' => 'index.sd', 'uses' => 'App\Http\Controllers\ContentController@sd']);
Route::get('/kiev', ['as' => 'index.kiev', 'uses' => 'App\Http\Controllers\ContentController@kiev']);
Route::get('/map', ['as' => 'map', 'uses' => 'App\Http\Controllers\ContentController@map']);

//pages area
Route::get('/saltovka', ['as' => 'index.saltovka', 'uses' => 'App\Http\Controllers\ContentController@saltovka']);
Route::get('/alekseevka', ['as' => 'index.alekseevka', 'uses' => 'App\Http\Controllers\ContentController@alekseevka']);
//page machines
Route::get('/bosch', ['as' => 'index.bosch', 'uses' => 'App\Http\Controllers\ContentController@bosch']);
Route::get('/electrolux', ['as' => 'index.electrolux', 'uses' => 'App\Http\Controllers\ContentController@electrolux']);
Route::get('/indesit', ['as' => 'index.indesit', 'uses' => 'App\Http\Controllers\ContentController@indesit']);
Route::get('/samsung', ['as' => 'index.samsung', 'uses' => 'App\Http\Controllers\ContentController@samsung']);
Route::get('/zanussi', ['as' => 'index.zanussi', 'uses' => 'App\Http\Controllers\ContentController@zanussi']);
Route::get('/ariston', ['as' => 'index.ariston', 'uses' => 'App\Http\Controllers\ContentController@ariston']);
Route::get('/ardo', ['as' => 'index.ardo', 'uses' => 'App\Http\Controllers\ContentController@ardo']);
Route::get('/lg', ['as' => 'index.lg', 'uses' => 'App\Http\Controllers\ContentController@lg']);





Route::get('/streaming', 'App\Http\Controllers\WebrtcStreamingController@index');
Route::get('/streaming/{streamId}', 'App\Http\Controllers\WebrtcStreamingController@consumer');
Route::post('/stream-offer', 'App\Http\Controllers\WebrtcStreamingController@makeStreamOffer');
Route::post('/stream-answer', 'App\Http\Controllers\WebrtcStreamingController@makeStreamAnswer');

app/Models/TypeOfTechnic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TypeOfTechnic extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'image',
        'description',
        'is_active',
    ];

    public $timestamps = false;

    //Связь со всеми статьми
    public function post()
    {
        return $this->hasMany(Post::class, 'type_of_technic_id', 'id');
    }
}

app/Http/Controllers/Admin/TypeOfTechnicController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\UploadFileController;
use App\Http\Requests\Admin\Searches\TypeOfTechnicSearchRequest;
use App\Http\Requests\Admin\TypeOfTechnicCreateRequest;
use App\Http\Requests\Admin\TypeOfTechnicUpdateRequest;
use App\Models\TypeOfTechnic;
use App\Repositories\Admin\TypeOfTechnicRepository;
use Intervention\Image\ImageManagerStatic as Image;

class TypeOfTechnicController extends Controller
{
    /**
     * @var TypeOfTechnicRepository
     *
     * @var mixed
     */
    private $type_of_technic;

    /**
     * Переменная для загрузки фото
     *
     * @var mixed
     */
    private $image_path = [
            'path' => 'uploads_images/type_of_technics',
            'options' => 'public',
        ];

    /**
     * Переменная для инициализации класса загрузки фото
     */

    private $upload_image;

    public function __construct()
    {
        parent::__construct();

        $this->type_of_technic = app(TypeOfTechnicRepository::class);
        $this->upload_image = app(UploadFileController::class);
    }
    /**
     * Display a listing of the resource.
     *
     * @return mixed
     */
    public function index()
    {
        $type_of_technics = $this->type_of_technic->getAllWithPaginate(20);

        return view('admin.type_of_technics.index', compact('type_of_technics'));
    }

    /**
     * Show the form for creating a new resource.
     *
//     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.type_of_technics.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(TypeOfTechnicCreateRequest $request)
    {
        $data = $request->all();

        $data['image'] = $this->upload_image->saveSmallImage($request, $this->image_path);

        $result = TypeOfTechnic::create($data);

        if ($result) {
            return redirect()
                ->route('admin.type_of_technics.index')
                ->with(['success' => "Создано успешно"]);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка создания'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return mixed
     */
    public function show($id)
    {
        $type_of_technic = $this->type_of_technic->getShow($id);

        if (empty($manufacturer)) {
            return back()
                ->withErrors(['msg' => "Запись с идентификатором - [{$id}] не найдена"]);
        }

        return view('admin.type_of_technics.show', compact('type_of_technic'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return mixed
     */
    public function edit($id)
    {
        $type_of_technic = $this->type_of_technic->getEdit($id);

        return view('admin.type_of_technics.edit', compact('type_of_technic'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return mixed
     */
    public function update(TypeOfTechnicUpdateRequest $request, $id)
    {
        $data = $request->all();

        $type_of_technic = TypeOfTechnic::find($id);

        $data['image'] = $this->upload_image
            ->saveSmallImage($request, $this->image_path, $type_of_technic->getOriginal('image'));

        if (empty($type_of_technic)) {
            return back()
                ->withErrors(['msg' => "Запись с идентификатором - [{$id}] не найдена"])
                ->withInput();
        }

        $result = $type_of_technic->update($data);

        if ($result) {
            return redirect()
                ->route('admin.type_of_technics.index')
                ->with(['success' => 'Сохранено успешно']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return mixed
     */
    public function destroy($id)
    {
        $tot = $this->type_of_technic->getOne($id);

        if ($tot->post->count()) {
            $errors[] = 'Нельзя удалять технику, привязанную к статьям';
        }

        if(isset($errors)) {
            return back()->withErrors($errors);
        }
        //Удаление файла вместе с удалением записи
//        $image = $tot->image;
//        dd($image);
//        if ($image) {
////            \Storage::disk('public')->delete('/storage/' . $image);
//            dd(\Storage::disk('public')->delete('/storage/' . $image));
//        }

        $result = TypeOfTechnic::find($id)->forceDelete();

        if($result) {
            return redirect()
                ->route('admin.type_of_technics.index')
                ->with(['success' => 'Успешно удалено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка удаления!']);
        }
    }

    /**
     * Поиск по полю title
     */
    public function search(TypeOfTechnicSearchRequest $request)
    {
        $type_of_technics = $this->type_of_technic->getSearch($request);

        return view('admin.type_of_technics.index', compact('type_of_technics'));
    }
}

resources/views/admin/type_of_technics/create.blade.php
@extends('admin.layouts.app_create_template')

@section('title', 'Созадание категории')

@section('content')

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Новая категория</h1>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Новый тип техники</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10">
                        <!-- general form elements disabled -->
                        <div class="card card-warning">

                            <div class="card-body">
                                @php /** @var \App\Models\Manufacturer */ @endphp
                                <form method="POST" action="{{route('admin.type_of_technics.store')}}" enctype="multipart/form-data">
                                    @method('POST')
                                    @csrf

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="col-form-label" for="inputSuccess">
                                                    Название Производителя
                                                    @error('title') Не менее 5х символов @enderror
                                                </label>
                                                <input type="text" name="title"
                                                       minlength="3"
                                                       class="form-control @error('title') is-invalid @enderror"
                                                       placeholder="Заголовок ..."
                                                       value="{{ old('title') }}"
                                                >
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label" for="inputSuccess">
                                                    Краткое описание
                                                    @error('description') Не менее 5х символов @enderror
                                                </label>
                                                <textarea class="form-control @error('description') is-invalid @enderror"
                                                          name="description" minlength="5"
                                                          id="exampleFormControlTextarea1" rows="5">
                                                    {{ old('description') }}
                                                </textarea>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label" for="inputSuccess">
                                                    Загрузка картинки
                                                </label>
                                                <br>
                                                <div class="col-md-6">
                                                    <input type="file" id="file" name="image" class="form-control">
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="form-check">
                                                    <input type="hidden" name="is_active" value="0">
                                                    <input class="form-check-input" type="checkbox" name="is_active" value="1" checked>
                                                    <label class="form-check-label">Опубликовать</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="row">
                                                <span id="output"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <input class="btn btn-primary" type="submit" value="Сохранить">
                                </form>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>

                    <div class="col-md-2">
                        <a href="{{route('admin.type_of_technics.index')}}" class="btn btn-primary btn-block mb-3">Все производители</a>
                    </div>
                    <!--/.col (right) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    @include('admin.layouts.includes.preview_image')

@endsection()

resources/views/admin/type_of_technics/edit.blade.php
@extends('admin.layouts.app_create_template')

@section('title', 'Редактирование')

@section('content')

    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Редактируем категорию</h1>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Редактируем </li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10">
                        <!-- general form elements disabled -->
                        <div class="card card-warning">
                            <div class="card-body">
                                @php /** @var \App\Models\Manufacturer */ @endphp
                                <form method="POST"
                                      action="{{route('admin.type_of_technics.update', $type_of_technic->id)}}"
                                      enctype="multipart/form-data">
                                    @method('PATCH')
                                    @csrf
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="col-form-label" for="inputSuccess">
                                                    Название Производителя
                                                    @error('title') Не менее 5х символов @enderror
                                                </label>
                                                <input type="text" name="title"
                                                       minlength="3"
                                                       class="form-control @error('title') is-invalid @enderror"
                                                       placeholder="Заголовок ..."
                                                       value="{{ $type_of_technic->title }}"
                                                >
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label" for="inputSuccess">
                                                    Краткое описание
                                                    @error('title') Не менее 5х символов @enderror
                                                </label>
                                                <textarea class="form-control" name="description"
                                                          id="exampleFormControlTextarea1" rows="5">
                                                    {{ $type_of_technic->description }}
                                                </textarea>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label" for="inputSuccess">
                                                    Загрузка картинки
                                                </label>
                                                <br>
                                                <div class="col-md-6">
                                                    <input type="file" id="file" name="image" class="form-control">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="form-check">
                                                    <input type="hidden" name="is_active" value="0">
                                                    <input class="form-check-input"
                                                           type="checkbox" name="is_active" value="1"
                                                           @if($type_of_technic->is_active)
                                                               checked="checked"
                                                        @endif
                                                    >

{{--                                                    <input class="form-check-input" type="checkbox" name="is_active" value="1" checked>--}}
                                                    <label class="form-check-label">Опубликовать</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <img src="{{asset('/uploads_images/type_of_technics/small/' . $type_of_technic->image)}}"
                                                     alt="{{$type_of_technic->title}}" class="img-thumbnail">
                                            </div>
                                            <div class="row">
                                                <span id="output"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <input class="btn btn-primary" type="submit" value="Сохранить">
                                </form>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>

                    <div class="col-md-2">
                        <a href="{{route('admin.type_of_technics.index')}}" class="btn btn-primary btn-block mb-3">Все категории</a>

                        <form method="POST" action="{{route('admin.type_of_technics.destroy', $type_of_technic->id)}}">
                            @method('DELETE')
                            @csrf
                            <button type="submit"  class="btn btn-danger btn-block mb-3">
                                <i class="fas fa-trash"></i>
                                Удалить
                            </button>
                        </form>
                    </div>
                    <!--/.col (right) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    @include('admin.layouts.includes.preview_image')

@endsection()

resources/views/admin/type_of_technics/show.blade.php
@extends('admin.layouts.app')

@section('title', "Производитель - {{$manufacturer->title}}")

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1><b>Производитель -</b>{{$manufacturer->title}}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('admin.home')}}">Home</a></li>
                            <li class="breadcrumb-item active">{{$manufacturer->title}}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- /.col -->
                    <div class="col-md-9">
                        <div class="card card-primary card-outline">
                            <div class="card-header">
{{--                                <h3 class="card-title">{{$manufacturer->title}}</h3>--}}
                                <img class="img-fluid" src="{{asset('/storage/' . $manufacturer->image)}}"
                                     alt="{{$manufacturer->title}}" class="img-thumbnail">
                            </div>
                            <div class="col-md-6">
                                <div class="card-body p-0">
                                    <!-- /.mailbox-controls -->
                                    <div class="mailbox-read-message">
                                        <b>Текст:</b>
                                        <br>
                                        {!! $manufacturer->description !!}
                                    </div>
                                    <!-- /.mailbox-read-message -->
                                </div>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>


                    <div class="col-md-3">
                        <a href="{{route('admin.manufacturers.create')}}" class="btn btn-primary btn-block mb-3">Сохдать</a>
                        <a href="{{route('admin.manufacturers.index')}}" class="btn btn-primary btn-block mb-3">Все</a>
                        <a href="{{route('admin.manufacturers.edit', $manufacturer->id)}}" class="btn btn-primary btn-block mb-3">Редактировать</a>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection()